spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://gaguena-dev:5432/chinook
    username: postgres
    password: 1234

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
